Assignment-4
abhishek-dash/10x-Acad-Assignment4 pull request #1
Opened 2021-11-13 12:01 UTC by abhishek-dash

2021-11-15 06:05 UTC, G4GANCHAUDHARY commented on format.html
> +</html>
Did a decent job there!

2021-11-15 06:08 UTC, G4GANCHAUDHARY commented on image.html
> +<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto optio nobis exercitationem placeat animi ducimus. Aliquid est quae dolores rerum atque hic tempore quas? Laborum eum explicabo corru
You could have used super tags there but this also does the job. I would suggest to always give basic super tags to html file.

2021-11-15 06:10 UTC, G4GANCHAUDHARY requested changes
Overall, you have completed your assignment. but, I would suggest you to go through the comment on image.html file.

2021-11-16 03:58 UTC, saikiransathpadi commented
for activity 1, layout is correct could have used CSS to look better
try to use target="_blank" to open the page in a different tab on clicking the image
try to format the code to look the code cleaner

2021-11-18 15:51 UTC, Nocturnal22 commented
fb/twitter/insta/linkedin clickbaits not working.

2021-12-30 08:24 UTC, merged